# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('included_courses', models.ManyToManyField(related_name='referenced_courses', to='course_app.Course')),
                ('user_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to='login_app.User')),
            ],
        ),
    ]
