# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-28 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='included_courses',
            field=models.ManyToManyField(related_name='referenced_plans', to='course_app.Course'),
        ),
    ]
